
## Package documentation file.
##
## The file name is prefixed with `0_` , to ensure that it is processed first,
## so that @names/@rdnames are picked up here.
##
## It uses desc::desc_get() to get the description, instead of relying on
## autogenerated description. This is done in order to get markdown parsing and
## facilitate adding extra text to the package doc in addition to the text from
## the DESCRIPTION file.


#' @description
#' `r desc::desc_get("Description")`
#'
#' To get started, check out the help for the [gitpin()] function, or take a
#' look at the info on GitHub (see links below).
#'
#'
#' @docType package
#' @name gitpins
#' @md
#' @keywords internal
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL
